runtime: python38
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
- url: /static
  static_dir: www/static/

- url: /.*
  script: auto

env_variables:
  TRAVELER_PW: MamanYouss

beta_settings:
  cloud_sql_instances: wishlist-274905:us-central1:wishlisted-db